PX4/NuttX branch test: master
NuttX:
 - https://github.com/PX4-NuttX/nuttx/tree/master
 - https://github.com/PX4-NuttX/nuttx/commit/43f00705824157a6963a908ed75f88fa19df96b3

Changes from PX4/NuttX (https://github.com/PX4/NuttX/commit/1c488eb864ff657474f97c342ec5c8fcd2bcb7fd) in current PX4/master (8b26b84fd195b8ab5f0cbe2e0a69d6356c21ccda)
https://github.com/PX4/NuttX/compare/1c488eb864ff657474f97c342ec5c8fcd2bcb7fd...43f00705824157a6963a908ed75f88fa19df96b3

43f0070582 (HEAD, origin/master) fs: Simplify the symbol link process in inode_search
f4794f0b48 libc: Implement access function correctly
a1c047fe53 libc/uio: enable writev() for sockets
65bb956e5e pipe: check for writers first in case of pipe empty
a128995eab arch/xtensa: Few typos and style fixes.
bc9d3cdd14 tiva: tiva_flash.h: Fix nxstyle warnings
b8b4055cb1 RX65N Pre-check Warning Resolved
68a2727c12 arch/sim: Extend the heap size to 64MB
411f5d591a sched: Fix undefined reference to 'sched_cpu_count'
ba3f12c93f libc: Implement popcount/popcountl/popcountll

Apps:
 - https://github.com/PX4/NuttX-apps/tree/master
 - https://github.com/PX4/NuttX-apps/commit/df389bc3322af9e7004a855c82a10daff978c4ec

Changes from PX4/NuttX-apps (https://github.com/PX4/NuttX-apps/commit/3edfb4a3acc0d01838d01367c2f5f7da9b1db57f) in current PX4/master (8b26b84fd195b8ab5f0cbe2e0a69d6356c21ccda)
https://github.com/PX4/NuttX-apps/compare/3edfb4a3acc0d01838d01367c2f5f7da9b1db57f...df389bc3322af9e7004a855c82a10daff978c4ec

df389bc3 (HEAD -> master, origin/master) apps/Application.mk: fix compile assmbely error
e8a353af netutils: dhcpc: Fix dhcpc.c
d635fcb2 application.mk: fix multi MAINSRC match suffix in single Makefile
3c4089ef apps/MAKE: Add register staging to context
3061dbf2 wireless/wapi: add option to associate with bssid
a0f6b14c wireless/wapi: add scan partial channel support
77aa0e89 netutils/dhcpc: try to get the host name via syscall first
40f559bf wireless/wapi: ignore the fail case
1b9c307e make/import: lost ARCHCPUFLAGS in cxx command line
69956020 interpreters/wamr: Add missing options